App_Profile/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('profile', views.profilePage, name='profile_page'), #alamat di web, fungsi yg diakses, namespace(semacam var akses)
	path('profile/check/email/is_taken', views.emailValidation, name='email_validation'),
	path('profile/create/new_user', views.createUser, name='create_user'),
	path('profile/get/subscriber/subscriber_list', views.subscriberList, name='subscriber_list'),
]

SecondWebsite/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_HelloLandingPage.urls')),
    path('', include('App_Profile.urls')),
    path('', include('App_Bookshelf.urls')),
    path('', include('App_Login.urls')),
    path('', include('App_LatihanUas.urls')),
    path('', include('TEST.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

TEST/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('twitter/alkautsr/tweets/191803308191', views.test, name='test_app')
]

App_Profile/models.py
from django.db import models

# Create your models here.
class RegistrationModels(models.Model) :
	nama = models.CharField(max_length=30, default='')
	email = models.EmailField(max_length=100, default='')
	password = models.CharField(max_length=35, default='')

App_Profile/forms.py
from django import forms

class RegistrationForm(forms.Form) :
	namaForm = forms.CharField(label="Nama", max_length=35,
		widget = forms.TextInput(attrs={'placeholder':'Tuliskan nama...', 'class':'form-control'}))
	emailForm = forms.EmailField(label="Email", max_length=100,
		widget = forms.EmailInput(attrs={'placeholder':'Tuliskan email...', 'class':'form-control'}))
	passwordForm = forms.CharField(label="Password", min_length=8, max_length=35,
		widget = forms.PasswordInput(attrs={'placeholder':'Tuliskan password...', 'class':'form-control'}))

App_Profile/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse

from .forms import RegistrationForm
from .models import RegistrationModels

import json

mhs_name = 'Muhammad Al-Kautsar Maktub' 
birth_date = "18 Januari 1999"
npm = 1706043885 
tempat_kuliah = 'Universitas Indonesia'
hobi = 'Mempelajari hal-hal yang baru'
deskripsi = 'Saya berkuliah di UI. Saya orang yang suka mempelajari \
hal-hal baru.'

def profilePage(request) :
	response = {'name': mhs_name,  'tgl_lahir':birth_date, 'npm': npm, 
	'tempatkuliah' : tempat_kuliah, 'hobi' : hobi, 'deskripsi' : deskripsi, 'form':RegistrationForm()}

	return render(request, 'profile_page.html', response)

def emailValidation(request) :
	emailFilled = request.GET.get('emailForm', None)
	data = {
		'is_taken':RegistrationModels.objects.filter(email = emailFilled).exists()
	}
	return JsonResponse(data)

def createUser(request) :
	registrationForm =  RegistrationForm(request.POST or None)
	condition = {'condition':'Success'}
	
	if(request.method == 'POST' and registrationForm.is_valid()) :
		nama_user = request.POST['namaForm']
		email_user = request.POST['emailForm']
		password_user = request.POST['passwordForm']

		registrationModel = RegistrationModels(nama = nama_user, email = email_user,
			password = password_user)
		registrationModel.save()
	else  :
		if (list(registrationForm.errors.as_data().keys())[0] == 'emailForm') : #kl sy test ini dgn akses page(status code 200), error krn [0]nya blm ada tpi kl udh jd web sabi
			condition['condition'] = 'Failed. Please enter correct email.'
		elif (list(registrationForm.errors.as_data().keys())[0] == 'passwordForm') :
			condition['condition'] = "Failed. Please make sure total password's characters not more than 35 and not less than 8."
		
	return JsonResponse(condition)

def subscriberList(request) :
	allSubscriber = RegistrationModels.objects.all().values()
	subscriberList = []
	data = {'data' : []}

	if(request.method == 'POST') :
		emailFilled = request.POST['email']
		RegistrationModels.objects.filter(email = emailFilled).delete()

	else :	
		for x in range (len(allSubscriber)) :
			subscriberList.append({'nama':allSubscriber[x]['nama'], 'email':allSubscriber[x]['email']})

		data['data'] = subscriberList
	return JsonResponse(data)

App_Profile/templates/profile_page.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
	<title>Profile</title>
	<!-- Kenapa tidak bisa kl jquery dibawah ini di base??? cb tanya asdos-->
	<script src="{% static 'App_Profile\jquery-ui-1.12.1.custom\external\jquery\jquery.js' %}"></script>
	<script src="{% static 'App_Profile\jquery-ui-1.12.1.custom\jquery-ui.min.js' %}"></script>
</head>

<body style="background-color: #004A64FF;"  id="id_profile">

	<div class="row" id="main">
		<div class="col align-items-center">
			<img class="row" src="{% static 'App_Profile\img\profile.jpg' %}" alt="" id="id_fotoProfil" style="margin-left: 7vw;">
		</div>
		
		<div class="col">
			<div class="row">
				<p id="id_profilUmum">
					Nama 						:	{{name}}<br>
					Tanggal lahir 	:	{{tgl_lahir}}<br>
					NPM 						: {{npm}}<br>
					Kuliah 					: {{tempatkuliah}}<br>
					Hobi 						: {{hobi}}<br>
					Deskripsi diri 	: {{deskripsi}}<br>
				</p>
			</div>
		
			<div class="row" style="margin-right: 2.5vw">
				<div class="col" id="accordion">
					<h3 style="font-size: 2vw">Aktivitas</h3>
				  <div>
				  	<p style="font-size: 1vw">
				  		Aktivitas saya saat ini adalah berkuliah serta menjalankan beberapa organisasi dan kepanitiaan.
				  	</p>
				  </div>
				  <h3 style="font-size: 2vw">Kepanitiaan dan Organisasi</h3>
				  <div>
				  	<p style="font-size: 1vw">
				  		- Sekretaris SAIMALA UI 2018/2019 <br>
				  		- Staf Dept. Kajian dan Aksi Strategis BEM Fasilkom UI 2018 <br>
				  		- VPO TOBK SAIMALA El Dorado 2019 <br>
				  		- WaPJ Hubungan Eksternal OKK UI 2018 <br>
				  	</p>
				  </div>
				  <h3 style="font-size: 2vw">Prestasi</h3>
				  <div>
				  	<p style="font-size: 1vw">
				  		Mohon maaf prestasi tidak ditemukan. :)
				  	</p>
				  </div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div style="margin-left: 2rem;margin-right: 2rem">
		<div class="text-center" style="color: white;">
			<div><h4>Subscribe</h4></div><br>
			<form id="id_form" method="POST" action="">
				{% csrf_token %}
				{{form}}
				<br>
				<button class="btn" id="id_btn" type="submit" action="POST">Submit</button>
			</form>
		</div>
		<br>
		<div class="text-center" style="color: white;">
			<div><h4>Subscriber List</h4></div><br>
			<ul id="id_subscriberlist" class="list-group" style="color: black"></ul>
		</div>
	</div>
</body>

<script>
	var nama = ""
	var email = ""
	var password = ""

	$(document).ready(function(e){
		function subscriberList_func(){
			$.ajax({
				url: "/profile/get/subscriber/subscriber_list",
				dataType: "json",
				success:function(result){
					$("#id_subscriberlist").empty()
					for(var i = 0;i < result.data.length; i++){
						$('#id_subscriberlist').append('<li class="list-group-item">' + result.data[i].nama + ' ' + result.data[i].email + '<br><button type="button" id="'+ result.data[i].email + '" class="unsubscribebtn btn btn-danger text-right">Unsubscribe</button></li>')
					}
				}
			});
		}
		
		subscriberList_func() //CALLING SUBSCRIBER LIST AT FIRST TIME

		$("#id_subscriberlist").on('click', ".unsubscribebtn", function(){ //posisi skrg thisnya di list-group-item
			$.ajax({
				url: "/profile/get/subscriber/subscriber_list",
				method: "POST",
				data:{
					"email" : $(this).attr('id'),
					'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken').val(),
				},
				success:function(result){
					alert("Success delete bro")
					subscriberList_func();
				}
			})
		});

		$( ":input[type='submit']" ).click(function(){
			$.ajax({
				url: "/profile/create/new_user",
				method: "POST",
				data:{
					'namaForm':nama,
					'emailForm':email,
					'passwordForm':password,
					'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken').val()
				},
				success:function(result){
					if(result.condition === 'Success'){
						alert("Created.");
						$('#id_namaForm').val("");
						$('#id_emailForm').val("");
						$('#id_passwordForm').val("");
						$( ":input[type='submit']" ).prop('disabled', true);
						subscriberList_func();
					}
					else{
						alert(result.condition)
					}
				}
			});
			return false;	//biar ga refresh
		});

		$( ":input[type='submit']" ).prop('disabled', true);	

		$( "#accordion" ).accordion({	
			collapsible : true,
			active : false
		});

		$( "#id_namaForm" ).change(function(){
			nama = $(this).val();
			if(nama != "" && email != "" && password !== ""){
				$( ":input[type='submit']" ).prop('disabled', false);
			}
			else{$( ":input[type='submit']" ).prop('disabled', true);}
		})

		$( "#id_passwordForm" ).change(function(){
			password = $(this).val();
			if(nama != "" && email != "" && password !== ""){
				$( ":input[type='submit']" ).prop('disabled', false);
			}
			else{$( ":input[type='submit']" ).prop('disabled', true);}
		})

		$( "#id_emailForm" ).change(function(){
			email = $(this).val()

			if(nama != "" && email != "" && password !== ""){
				$( ":input[type='submit']" ).prop('disabled', false);
			}
			else{$( ":input[type='submit']" ).prop('disabled', true);}

			$.ajax({
				url: "/profile/check/email/is_taken",
				dataType: "json",
				data:{
					'emailForm':email
				},
				success:function(result){
					if(result.is_taken){
						alert("Email is already exist")
						$( ":input[type='submit']" ).prop('disabled', true);		
					}
				},
				error:function(error){
					console.log(error)	
				}
			});
		});
	});
</script>

{% endblock %}