App_LatihanUas/urls.py
from django.conf.urls import url
from .views import index, add_item

app_name = 'prc'

urlpatterns = [
	url(r'^latihan-uas$', index, name='index'),
	url(r'^add-item$', add_item, name='add-item'),
]

SecondWebsite/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_HelloLandingPage.urls')),
    path('', include('App_Profile.urls')),
    path('', include('App_Bookshelf.urls')),
    path('', include('App_Login.urls')),
    path('', include('App_LatihanUas.urls')),
    path('', include('TEST.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

TEST/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('twitter/alkautsr/tweets/191803308191', views.test, name='test_app')
]

App_LatihanUas/models.py
from django.db import models

# Create your models here.
class Keranjang(models.Model) :

	barang = models.CharField(max_length=100)
	created_date = models.DateField(auto_now=True)

App_LatihanUas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Keranjang

def index(request):
	response = {'item':Keranjang.objects.all().values()}

	return render(request, 'belanja.html', response)

def add_item(request):
	if(request.POST) :
		Keranjang.objects.create(barang = request.POST['barang'])
		Keranjang.save()
		
	return HttpResponseRedirect('/latihan-uas')

App_LatihanUas/templates/belanja.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Title</title>
		<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	</head>

	<body>
		<form method="POST" action="{% url 'prc:add-item' %}">
			{% csrf_token %}
			<label id="label_barang" for="barang">Barang : </label><input type="text"
			id="barang" class="abc" name="barang" oninput="typingsomething()">
			<input type="submit" value="submit" onclick="alert('Value Submitted')" />
		</form>
		<h1>Keranjang Belanja</h1>

		<table id="list_belanja">
			{% for it in item %}
			<tr>
				<td class="item" id="{{ it.id }}_barang">{{ it.barang }}</td>
				<td class="item" id="{{ it.id }}_tanggal_belanja">{{ it.created_date }}</td>
			</tr>
			{% endfor %}
		</table>
	</body>

	<script>
	var typingsomething = function(){
		console.log($('.abc').val())
	};
	$('h1').attr("style","font-style:italic")
	$('#list_belanja').attr("style","background-color:green")
	</script>
</html>